/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)

const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/cliente': typeof ClienteIndexRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/cliente': typeof ClienteIndexRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/': typeof AdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendar' | '/blog' | '/blog/$slug' | '/servicos/$slug' | '/auth/login' | '/cliente' | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendar' | '/blog' | '/blog/$slug' | '/servicos/$slug' | '/auth/login' | '/cliente' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/blog'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/auth/login'
    | '/cliente/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  BlogRoute: typeof BlogRouteWithChildren
  ServicosSlugRoute: typeof ServicosSlugRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  BlogRoute: BlogRouteWithChildren,
  ServicosSlugRoute: ServicosSlugRoute,
  AuthLoginRoute: AuthLoginRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
